### ISSUE TITLE
'Flickering' when some images get displayed

### ISSUE THREAD

**Issue by robsch** [simogeo/Filemanager#334]
I just noticed that on http://fm.linea21.com: When I click on an image so that it gets shown in the right area and it has a certain size than some 'flickering' starts. It seems that the scroll bar get shown and hidden all the time. To see it you have to resize the browser vertically so that the scrollbar is almost (not) needed. As soon as you make the browser window bigger (scrollbar gone) or smaller (scrollbar needed) the flickering disappears.

Currently you can use picture Untitled-1.jpg as an example.

I can reproduce this in Firefox 31 and Google Chrome 41.

**Comment by simogeo** [comment]
Tested in Google Chrome 18 and FF37 but it seems I can't reproduce the bug. 
Precision and / or other users feedback is wanted. Thanks

**Comment by robsch** [comment]
You should see it as well. I'm on Mac but I have tried it also on Windows with IE. Same effect here.

See the red pointer and the scrollbar that is about 95%? If it is about this size (+/- 10 pixel or so) the right pane flickers. The scrollbar displays and hides. Approximately about 5 times per second.

![bildschirmfoto 2015-04-09 um 15 38 29](https://cloud.githubusercontent.com/assets/2900992/7067953/56bf7684-decf-11e4-8d60-5ba8c572c8aa.png)

**Comment by robsch** [comment]
Ah, and this seems only to happen if the image was resized. So you have to make the window horizontally smaller (and then vertically) to see it. If the image is not resized it doesn't happen.

**Comment by simogeo** [comment]
Indeed, I could observed the neurotic behaviour when reaching the limit of scroll need ! I guess it is due to custom-scrollbar plugin itself so I referenced the issue on the repo itself (see above).

Regarding the [doc]()http://manos.malihu.gr/jquery-custom-content-scroller, I may fix this by adding by default `alwaysShowScrollbar: 1` option / value. But this would add the dragger rail in any page.

I hope the plugin author will propose a better fix.

**Comment by simogeo** [comment]
0c8540edd786e26bbf60dad0f4b86272e137dcd7
