### ISSUE TITLE
How to do with a long list of files

### ISSUE THREAD

**Issue by kabeda** [simogeo/Filemanager#510]
Hi,
I have in one of my folders more than ten thousands of files (Yes more than 10.000 files). When I access with filemanager I got an error. In my log I found this kind of error
_PHP Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 8192 bytes) in /home/user/public_html/filemanager/connectors/php/filemanager.class.php on line 1290_

Should it be possible to have paginated list instead of this long list ?
I'm using the laravel version of @bestmomo.

**Comment by simogeo** [comment]
Hi,
There is no plan for further development ...  If anyone propose a new feature -  such as pagination, it will of course be integrated into the trunk (if proposed code is clean). But since RichFilemanager is the new version of the FM I let @servocoder tell you what will happen regarding this.

You can try to allocate more memory, but this not a clean and sustainable solution

**Comment by servocoder** [comment]
Interesting feature request, I will note it and consider later to check the capability for paginated list. It also may be lazy loading list as an option. Will see.

**Comment by kabeda** [comment]
Hi,
In fact, our actual website is using vivvo and in their filepicker (similar as filemanager), they start by saving the listing of the folders in a table in database just after logging in the admin location. Then when the filepicker is requested, they just display the result with pagination.

Hope will serve.

**Comment by simogeo** [comment]
The approach seems great. I think it should be done in a flat file regarding the (R)FM.
